### ISSUE TITLE
Switch to Buildkite ECS plugin

### ISSUE THREAD

**Issue by toolmantim** [buildkite/site#422]
We've ended up in a pickle where we can't really use the [Buildkite ECS plugin](https://github.com/buildkite-plugins/ecs-deploy-buildkite-plugin) to replace:
https://github.com/buildkite/site/blob/master/scripts/deploy-ecs

I wonder what it'd take to be able to use it?

@patrobinson do you have any feels for what we need, vs how you're using it?

**Comment by patrobinson** [comment]
@toolmantim what issues are you facing?

**Comment by toolmantim** [comment]
I think perhaps all the create/target group is what @lox was thinking we didn't need. Although it appears they're all actually optional, but not listed as optional in the readme.

Aside from that, I think it actually looks like it will just work for what we want, if we just switch the task JSON to be stored in the repo! 🙌🏼
