### ISSUE TITLE
Broken URL in Pipeline Visibility

### ISSUE THREAD

**Issue by andreeaflorescu** [buildkite/site#427]
In the Pipeline Settings -> General -> Pipeline Visibility one of the URLs to the Community Forum is linking an invalid page. Response from clicking on the URL: "Oops! That page doesn’t exist or is private."

The invalid URL: https://forum.buildkite.community/c/beta-public-builds

![buildkite_bug](https://user-images.githubusercontent.com/2815944/58896936-c1570980-86ff-11e9-9dc1-c15d3899642e.png)

**Comment by plasticine** [comment]
@andreeaflorescu Oh dear — thanks, I’ll get this fixed up!
